export const tables = [
    {
        name: 'application',
        cols: [
            'id integer primary key not null',
            'version varchar not null',
            'device_id varchar not null',
            'uid_prefix varchar not null',
            'mode varchar not null',
            'last_sync_date datetime',
            'total_sessions_recorded integer',
            'webeditor_info text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'scripts',
        cols: [
            'id varchar primary key not null',
            'script_id varchar',
            'type varchar',
            'position integer',
            'data text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'screens',
        cols: [
            'id integer primary key not null',
            'script_id varchar',
            'screen_id varchar',
            'position integer',
            'type varchar',
            'data text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'diagnoses',
        cols: [
            'id integer primary key not null',
            'script_id varchar',
            'diagnosis_id varchar',
            'position integer',
            'type varchar',
            'data text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'sessions',
        cols: [
            'id integer primary key not null',
            'session_id integer',
            'script_id varchar',
            'type varchar',
            'uid varchar',
            'data text',
            'completed boolean',
            'exported boolean',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'exports',
        cols: [
            'id integer primary key not null',
            'session_id integer not null',
            'uid varchar',
            'scriptid varchar',
            'data text',
            'ingested_at datetime',
        ].join(','),
    },
    {
        name: 'authenticated_user',
        cols: [
            'id integer primary key not null',
            'authenticated boolean',
            'details text',
        ].join(','),
    },
    {
        name: 'config_keys',
        cols: [
            'id varchar primary key not null',
            'config_key_id varchar',
            'position integer',
            'data text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'configuration',
        cols: [
            'id varchar primary key not null',
            'data text',
            'createdAt datetime',
            'updatedAt datetime',
        ].join(','),
    },
    {
        name: 'location',
        cols: [
            'id integer primary key not null',
            'country varchar',
            'hospital varchar',
        ].join(','),
    },
];
