import constants from '@/constants';

export default function getJSON(_sessions = [], opts = {}) {
  const { showConfidential } = opts;

  const sessions = _sessions.map((s) => {
    const { script, form, completed_at, canceled_at, started_at } = s.data;

    const data = {
      uid: s.uid,
      appVersion: constants.APP_VERSION,
      scriptTitle: script.script_id,
      script: { id: script.script_id, title: script.data.title },
      start_time: started_at,
      end_time: completed_at || canceled_at,
      entries: form
        .map((e) => ({
          ...e,
          values: e.values.filter((v) =>
            v.confidential ? showConfidential : true
          ),
        }))
        .reduce((acc, e) => {
          const getVal = ({ value, dataType, type }) => {
            const t = dataType || type;
            switch (t) {
              case 'number':
                return Number(value) || null;
              case 'boolean':
                return value === 'false' ? false : Boolean(value);
              default:
                return value;
            }
          };

          return [
            ...acc,
            ...e.values.map((v) => {
              const {
                key,
                type,
                dataType,
                value,
                label,
                valueLabel,
                exportValue,
              } = v;
              return {
                key,
                type: dataType || type,
                values:
                  value && value.map
                    ? value.map(
                      ({ value, label, valueLabel, exportValue }) => ({
                        value: exportValue || value,
                        label: valueLabel || label,
                      })
                    )
                    : [
                      {
                        value: exportValue || getVal(v),
                        label: valueLabel || label,
                      },
                    ],
              };
            }),
          ];
        }, []),
    };
    //Format Data into new Format
    const formattedData = {
      ...data,
      ...data.entries.map((e) => {
        const labels = [];
        const values = [];
        return e.values.map((v) => {
          labels.push(v.label);
          values.push(v.value);
          e.values = { label: labels, value: values };
          return e;
        })[0];
      }),
    };
    // Remove Entries From The Formatted Entries To Avoid Redundancy
    delete formattedData.entries;
    // Create Empty Entries Object
    formattedData.entries = {};
    // Make the keys Objects within entries the upper level keys to replace the autogenerated keys
    Object.keys(formattedData).map((key) => {
      if (formattedData[key] != null && formattedData[key].key) {
        formattedData.entries[formattedData[key].key] = formattedData[key];
        //Remove The Keys From The Enties Object
        delete formattedData[key].key;
        // Remove The Autogenerated Keys From The Entries Obj
        delete formattedData[key];
      }
    });
    return formattedData;
  });

  return sessions;
}
