
export default function toNewJsonFormat(data = {}) {
//Format Data into new Format
const formattedData = {
  ...data,
  ...data.entries.map((e) => {
    const labels = [];
    const values = [];
    return e.values.map((v) => {
      labels.push(v.label);
      values.push(v.value);
      e["values"] = { label: labels, value: values };
      return e;
    })[0];
  }),
};
// Remove Entries From The Formatted Entries To Avoid Redundancy
delete formattedData.entries;
// Create Empty Entries Object
formattedData.entries = {};
// Make the keys Objects within entries the upper level keys to replace the autogenerated keys
Object.keys(formattedData).map((key) => {
  if (formattedData[key] != null && formattedData[key].key) {
    formattedData["entries"][formattedData[key].key] = formattedData[key];
    //Remove The Keys From The Enties Object
    delete formattedData[key].key;
    // Remove The Autogenerated Keys From The Entries Obj
    delete formattedData[key];
  }
});

return formattedData;
}