namespace NodeJS {
    interface ProcessEnv {
        NODE_ENV: string;
        NEOTREE_BUILD_TYPE: string;
		EXPO_PUBLIC_DB_LOGGER: string;
		EXPO_PUBLIC_WEBEDITOR_API_KEY: string;
		EXPO_PUBLIC_NODEAPI_API_KEY: string;
		EXPO_PUBLIC_DEV_COUNTRY_NAME: string;
		EXPO_PUBLIC_DEV_COUNTRY_ISO: string;
		EXPO_PUBLIC_DEV_WEBEDITOR_HOST: string;
		EXPO_PUBLIC_DEV_WEBEDITOR_API_ENDPOINT: string;
		EXPO_PUBLIC_DEV_WEBEDITOR_API_KEY: string;
		EXPO_PUBLIC_DEV_NODEAPI_HOST: string;
		EXPO_PUBLIC_DEV_NODEAPI_API_ENDPOINT: string;
		EXPO_PUBLIC_DEV_NODEAPI_API_KEY: string;
    }
}
