export const ASYNC_STORAGE_KEYS = {
    SYNC_ERROR: 'SYNC_ERROR',
    EXPORT_QUEUE: 'EXPORT_QUEUE',
    UPDATE_POLICY: 'UPDATE_POLICY',
    LAST_REPORTED_APP_STATE: 'LAST_REPORTED_APP_STATE',
    OTA_EVENTS_QUEUE: 'OTA_EVENTS_QUEUE',
    OTA_EVENTS_LAST_FLUSH: 'OTA_EVENTS_LAST_FLUSH',
    APK_DOWNLOAD_STATE: 'APK_DOWNLOAD_STATE',
    APK_DOWNLOAD_RESUME_DATA: 'APK_DOWNLOAD_RESUME_DATA',
    SESSION_ACTIVE: 'SESSION_ACTIVE',
    APK_INSTALL_DEFER_UNTIL: 'APK_INSTALL_DEFER_UNTIL',
    APK_DOWNLOAD_RETRY_AT: 'APK_DOWNLOAD_RETRY_AT',
};
