export const defaultState = {
  uid_prefix: null,
  loadingDataStatus: false,
  dataStatus: null,
  syncingData: false,
  lastDataSyncEvent: null,
  syncError: null,
  acceptedEvents: [],
  displaySplashScreen: false,
  splashScreenText: null,
  overlayLoaderState: {},
  networkState: null,
  networkStateInitialised: false,
  fontsLoaded: null,
  authenticatedUserInitialised: null,
  authenticatedUser: null,
  loadingAuthenticatedUser: null,
  adminpassword: '$2a$10$hyKNeHY/aAlO1oteuPZpWeA407gDqWqZYAqwz73m0ZjFn7DdRygJO',
};
