import React, { useMemo } from 'react';

import { useScriptContext } from '@/src/contexts/script';
import { Box,NeotreeIDInput, Text, TextInput} from '../../../../components';
import * as types from '../../../../types';


type TextFieldProps = types.ScreenFormTypeProps & {
    patientNUID?: string | null;
};


export function TextField({ 
    field, 
    conditionMet, 
    entryValue, 
    patientNUID,
    repeatable,
    editable ,
    onChange 
}: TextFieldProps) {
    const { generatedUID } = useScriptContext();
    const normalizedFieldKey = `${field?.key || ''}`.trim();
    const isNeotreeID = useMemo(() => {
        return /^uid$/i.test(normalizedFieldKey)
            || /^nuid$/i.test(normalizedFieldKey)
            || /^nuid_/i.test(normalizedFieldKey)
            || /neotree.*id/i.test(normalizedFieldKey)
            || field?.defaultValue === 'uid';
    }, [field?.defaultValue, normalizedFieldKey]);
	const prePopulatedUID = ''; // ctx.matched?.prePopulateWithUID ? ctx.matched?.uid : '';
    // const scriptType = script?.type
    // const isScanable = scriptType==='neolab' ||scriptType==='discharge'

    const [value, setValue] = React.useState(entryValue?.value || (isNeotreeID ? prePopulatedUID : '') || '');
    const [error, setError] = React.useState('');
    const [disabled, setDisabled] = React.useState(false);
    const canEdit = repeatable?editable:true
    const minCharacterLimit = useMemo(() => {
        const parsed = Number(field?.minLength);
        if (!Number.isInteger(parsed) || parsed <= 0) return undefined;
        return parsed;
    }, [field?.minLength]);
    const characterLimit = useMemo(() => {
        const parsed = Number(field?.maxLength);
        if (!Number.isInteger(parsed) || parsed <= 0) return undefined;
        return parsed;
    }, [field?.maxLength]);

    const getManualEntryError = React.useCallback((nextValue: string) => {
        if (nextValue && minCharacterLimit && nextValue.length < minCharacterLimit) {
            return `Minimum ${minCharacterLimit} characters`;
        }
        if (nextValue && characterLimit && nextValue.length > characterLimit) {
            return `Maximum ${characterLimit} characters`;
        }
        return '';
    }, [characterLimit, minCharacterLimit]);

    const emitValueChange = React.useCallback((nextValue: string, isManual = false) => {
        const normalizedValue = `${nextValue || ''}`;
        const nextError = isManual ? getManualEntryError(normalizedValue) : '';

        setValue(normalizedValue);
        setError(nextError);
        onChange({
            value: normalizedValue,
            valueText: normalizedValue,
            exportType: 'text',
            exportLabel: normalizedValue,
            label: field?.label,
            error: nextError || null,
        });
    }, [field?.label, getManualEntryError, onChange]);

    React.useEffect(() => { 
        if (!conditionMet) {
            onChange({ value: null, valueText: null, exportType: 'text',label: field?.label, error: null }); 
            setValue('');
            setError('');
        }
    }, [conditionMet, field?.label, onChange]);

    React.useEffect(() => {
        if (isNeotreeID && conditionMet && patientNUID) {
            onChange({ value: patientNUID, valueText: patientNUID, exportType: 'text',label: field?.label, error: null }); 
            setValue(patientNUID);
            setError('');
            setDisabled(true);
        }
    }, [conditionMet, patientNUID, field?.key, field?.label, isNeotreeID, onChange]);

    const autoGenerateValue = useMemo(() => !!field.defaultValue, [field]);

    return (
        <Box>
            {isNeotreeID ? (
                <>
                <NeotreeIDInput 
                    disabled={disabled || !conditionMet || (autoGenerateValue && (field.canEditAutoGeneratedValue !== true))}
                    defaultValue={prePopulatedUID}
                    label={`${field.label}${field.optional ? '' : ' *'}`}
                    value={value}
                    generatedUID={generatedUID}
                    onChange={(val, isManual) => emitValueChange(`${val || ''}`, !!isManual)}
                    autoGenerateValue={autoGenerateValue}

                />
                {!!error && (
                    <Text variant="caption" color="error">
                        {error}
                    </Text>
                )}
                </>
            ) : (
            
                <TextInput
                    multiline
                    editable={conditionMet && canEdit}
                    label={`${field.label}${field.optional ? '' : ' *'}`}
                    value={value}
                    errors={error ? [error] : []}
                    maxLength={characterLimit}
                    onChangeText={value => {                    
                        emitValueChange(value, true);
                    }}
                />
            
            )}
        </Box>
    );
}
