export const defaultState = {
  start_time: new Date().toISOString(),
  form: [],
  cachedForm: [],
  configuration: {},
  activeScreen: null,
  screenId: null,
  screens: [],
  activeScreenIndex: 0,
  loadingScreens: false,
  loadScreensError: null,
  screensInitialised: false,
  activeScreenInitialised: false,
  configKeysInitialised: false,
  loadConfigurationError: null,
  loadingConfiguration: false,
};
