export const NO_INTERNET = 'No internet connection';
export const PLEASE_WAIT = 'Please wait...';
export const HOME = 'Home';
export const HISTORY = 'History';
export const CONFIGURATION = 'Configuration';
export const SCRIPT = 'Script';
export const LOCATION = 'Location';
export const SAVE_ERROR = 'Failed to save';
export const LOGOUT = 'Logout';
