export * from './common';
export const LOAD_SCREENS_ERR = 'Failed to load screens';
export const LOAD_SCRIPT_ERR = 'Failed to load script';
export const NO_SCREENS = 'No screens found';
export const SCRIPT_NOT_FOUND = 'Script not found';
export const SCREEN_INFO = 'Screen info';
export const SELECT_TIME = 'Select time';
export const SELECT_DATE = 'Select date';
export const SELECT_DATE_AND_TIME = 'Select date and time';
export const START_TIMER = 'Tap to start';
export const STOP_TIMER = 'Tap to stop';
export const EXIT_SCRIPT_MODAL_TITLE = 'Cancel script';
export const EXIT_SCRIPT_MODAL_MESSAGE = 'Are you sure you want to cancel script?';
export const ALLOWED_UID_CHARS_ERR_PREFIX = 'Allowed characters:';
