name: Scheduled Security Scan

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scheduled:
    uses: neotree/security-ci/.github/workflows/scheduled-security.yml@8c4c9fab9f6f6c1c9bdac7ce29eb1e34506292d6
    permissions:
      contents: read
      security-events: write
      packages: read
    with:
      security-ci-ref: 8c4c9fab9f6f6c1c9bdac7ce29eb1e34506292d6
